version: '3.7'

services:
    postgres:
        image: postgres:13.0-alpine
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        env_file: .env
    factory_backend:
        build:
            context: ../backend
            dockerfile: ../backend/Dockerfile.dev
        depends_on:
            - postgres
        volumes:
            - ../backend:/backend
        command: /start.sh
        entrypoint: /entrypoint.sh
        env_file: .env
        ports:
            - "8001:8001"
    bot_polling:
        build:
            context: ../backend
            dockerfile: ../backend/Dockerfile.dev
        depends_on:
            - postgres
        volumes:
            - ../backend:/backend
        command: python -u run_polling.py
        entrypoint: /entrypoint.sh
        env_file: .env
