# Generated by Django 4.2 on 2023-10-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_bot_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
